### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by ghost** [BlackStar1313/Distributed-Database#1]
Hi!

Please tell me what type of license is used in your product?
Unfortunately I didn't found the license description file in your repository/

**Comment by NjoyimPeguy** [comment]
Hi @gvsafronov !

Indeed, I forgot to add a license. It will be the MIT one and I will close this issue.

Thanks!

**Comment by ghost** [comment]
I'm sorry to bother you, but I have two questions about your project:

1. Why in the configuration file  "config.txt" the values of the constants
start from one and not zero?
2. The value "82736" of the constant "COOKIE"  is a random number, isn't it?

*P.S.* I recently started learning Erlang and your brilliant project helps
me a lot, thank you very much!


*Best regards,Grigoriy Safronov*

пн, 27 мар. 2023 г. в 13:21, Njoyim Peguy ***@***.***>:

**Comment by NjoyimPeguy** [comment]
No problem.

Well for your two questions, it was a pure choice of mine. You can change it if you wish.
